### ISSUE TITLE
yml config for catalog with Json schema

### ISSUE THREAD

**Issue by gberche-orange** [spring-cloud/spring-cloud-open-service-broker#147]
I'm trying to use the yml syntax to configure a catalog with a Json schema. However, the "$schema" key seems converted into the "schema" key (i.e. the leading $ character is stripped out).

```yaml
spring:
  cloud:
    openservicebroker:
      catalog:
        services:
        - description: Description for Service One
          id: service-one-id
          name: Service One
[...]
          plans:
[...]
          - description: Description for Plan Two
            id: plan-two-id
            name: Plan Two
[...]
            schemas:
              serviceinstance:
                create:
                  parameters:
                    "$schema": "http://example.com/service/create/schema"
                    type: object
                update:
                  parameters:
                    "$schema": "http://example.com/service/create/schema"
                    type: object
# [...]
```

I'm unable to translate into YML format the properties syntax used in the test:

https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/4447ce296e65724d400111a526f5753442ddc151/spring-cloud-open-service-broker-autoconfigure/src/test/resources/catalog-full.properties#L27-L32

https://github.com/spring-cloud/spring-cloud-open-service-broker/commit/c2a78518de1e47bdd651606d8b14f76b9fa99e69 is a modified version of the test which reproduces the problem, and shows that the snakeyaml parsing properly parses the "$schema" property, but the spring `Binder` seems to strip out the leading $ when mapping it into the MethodSchema.parameters field.

The test fails with the following output:

```
java.lang.AssertionError: 
Expecting:
  <{"schema"="http://example.com/service/create/schema", "type"="object"}>
to contain only:
  <[MapEntry[key="$schema", value="http://example.com/service/create/schema"],
    MapEntry[key="type", value="object"]]>
elements not found:
  <[MapEntry[key="$schema", value="http://example.com/service/create/schema"]]>
and elements not expected:
  <[MapEntry[key="schema", value="http://example.com/service/create/schema"]]>

	at org.springframework.cloud.servicebroker.autoconfigure.web.ServiceBrokerPropertiesValidationTest.validateFullCatalog(ServiceBrokerPropertiesValidationTest.java:144)
	at org.springframework.cloud.servicebroker.autoconfigure.web.ServiceBrokerPropertiesValidationTest.bindFullValidYaml(ServiceBrokerPropertiesValidationTest.java:103)

```

Any suggestion on the right yml syntax to use properly define json schema ? I'll then submit the modified test as a PR to help other users with similar needs.

**Comment by royclarkson** [comment]
@gberche-orange well... after much experimentation I was able to get it to work using the following workaround. I copied your full YAML example and your test to validate it. Please feel free to submit a PR validating the full yaml. If you write the yaml like this, then it produces a property that is identical to the full java properties example.

```
schemas:
  serviceinstance:
    create:
      parameters[$schema]: http://example.com/service/create/schema
```
