### ISSUE TITLE
Catalog.services.plans.bindable is set as false when unconfigured

### ISSUE THREAD

**Issue by gberche-orange** [spring-cloud/spring-cloud-open-service-broker#153]
Given the following catalog.yml specified to configure the catalog

```yml
       spring:
         cloud:
           openservicebroker:
              catalog:
                services:
                - id: noop-ondemand-service
                  name: noop-ondemand
                  description: "On demand noop dedicated cluster"
                  bindable: true
                  plans:
                    - id: noop-ondemand-plan
                      name: default
                      description: Default plan (beta).
                      metadata:
                        displayName: ondemand noop
                        imageUrl:
                        longDescription: "A NoOp service used to test scalability of the COAB framework."
                        providerDisplayName: Orange
                        documentationUrl: https://github.com/orange-cloudfoundry/cf-ops-automation-broker/issues/38
                        supportUrl: https://github.com/orange-cloudfoundry/cf-ops-automation-broker/issues/38
                  tags:
                    - noop
                    - document
```

then the returned catalog to `/v2/catalog` endpoint includes a `plan.bindable: false` entry set by default by SCOSB

As a result, Cloudfoundry controller refuses users to execute `cf create-service-key` command with the message `This service doesn't support creation of keys.` 

OSB specs at https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#service-plan-object mention that plan.bindable field is optional and `If not specified, the default is derived from the Service Offering.`
