### ISSUE TITLE
catalog config does not support cloudfoundry plan metadata

### ISSUE THREAD

**Issue by gberche-orange** [spring-cloud/spring-cloud-open-service-broker#155]
The OSB specs at https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#service-metadata specifies that the plan metadata object may contain costs and bullets entries which are complex json objects and not simple values that are currently illustrated into 

https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/fecd6e17660ee75f9d1c566c33788aa1bb85f639/spring-cloud-open-service-broker-autoconfigure/src/test/resources/catalog-full.properties#L23-L24
and
https://github.com/spring-cloud/spring-cloud-open-service-broker/blob/fecd6e17660ee75f9d1c566c33788aa1bb85f639/spring-cloud-open-service-broker-autoconfigure/src/test/resources/catalog-full.yml#L33-L35

I could not find the right syntax for expressing the expected array for bullets and costs. 
I've tried to define such complex objects using properties or yml such as 

```
spring.cloud.openservicebroker.catalog.services[0].plans[1].metadata[key1]=value1
spring.cloud.openservicebroker.catalog.services[0].plans[1].metadata[key2]=value2
spring.cloud.openservicebroker.catalog.services[0].plans[1].metadata[displayName]=sample display name
spring.cloud.openservicebroker.catalog.services[0].plans[1].metadata.bullets[0]=bullet1
spring.cloud.openservicebroker.catalog.services[0].plans[1].metadata.bullets[1]=bullet2
spring.cloud.openservicebroker.catalog.services[0].plans[1].metadata.costs[0].amount[eur]=48.0
spring.cloud.openservicebroker.catalog.services[0].plans[1].metadata.costs[0].unit=Monthly
```

or 

```yaml
            metadata:
              key1: value1
              key2: value2
              displayName: "sample display name"
              bullets:
                - "bullet1"
                - "bullet2"
              costs:
                - amount:
                    eur: 649.0
                  unit: Monthly
```

but the resulting json output is instead (regardless of yml/properties source):

```json
{
[...]
  "metadata": {
    "key1": "value1",
    "costs": {
      "0": {
        "unit": "Monthly",
        "amount": {
          "eur": "48.0"
        }
      }
    },
    "key2": "value2",
    "displayName": "sample display name",
    "bullets": {
      "1": "bullet2",
      "0": "bullet1"
    }
  },
[...]
}
```
